<?php

namespace Kateshch\FaqBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FaqAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaqAnswerRepository extends EntityRepository
{


}
