<?php

namespace Kateshch\FaqBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\EntityRepository;
use Knp\DoctrineBehaviors\Model as ORMBehaviors;
use Symfony\Component\Validator\Constraints as Assert;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * @ORM\Entity()
 * @ORM\Table(name="app_faq_question_translations")
 */
class FaqQuestionTranslation
{
    use ORMBehaviors\Translatable\Translation;


    /**
     * @var string
     * @Assert\NotBlank(message="Please, enter your question!")
     * @ORM\Column(type="string",length=200, nullable=true)
     */
    protected $name;

    /**
     * @var string
     *
     * @ORM\Column(type="text")
     */
    protected $message;


    /**
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param string $name
     * @return $this
     */
    public function setName($name)
    {
        $this->name = $name;
        return $this;
    }

    /**
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * @param string $message
     * @return $this
     */
    public function setMessage($message)
    {
        $this->message = $message;
        return $this;
    }



}
