parameters:
  kateshch_faq.util.jsmodelprovider.class:
    Kateshch\FaqBundle\Service\Util\JsmodelProvider

services:
  iwin_app.util.jsmodelprovider:
    class: %kateshch_faq.util.jsmodelprovider.class%
    arguments:
      - %kateshch_faq.jsmodeldir%
    tags:
      - { name: werkint.requirejs }

